// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  softwareTeamSidebar: [
    "software-team/overview",
    "software-team/socket-communication",
    "software-team/python-opencv-mediapipe",
    "software-team/logging_tool",
    "software-team/ROS2 & Gazebo Documentation",
    "software-team/gtest",
    {
      type: "category",
      label: "Setup",
      items: [
        "software-team/setup/macos-setup",
        "software-team/setup/windows-setup",
      ],
    },
  ],
  mechanicalTeamSidebar: ["mechanical-team/overview",
    "mechanical-team/servo_driver"
  ],
  firmwareTeamSidebar: [
    "firmware-team/overview",
    "firmware-team/Sockets",
    "firmware-team/ROS2 & Gazebo Simulation",
  ],
  tutorialSidebar: [
    "intro",
    {
      type: "category",
      label: "Tutorial",
      items: [
        "tutorial-basics/create-a-document",
        "tutorial-basics/create-a-page",
        "tutorial-basics/markdown-features",
        "tutorial-extras/manage-docs-versions",
        "tutorial-extras/translate-your-site",
      ],
    },
  ],
};

export default sidebars;
