---
blank_issues_enabled: false  # Forces users to choose a template
contact_links:
  - name: Robot Arm Documentation
    url: https://sfu-akcse.github.io/Aether-docs/
    about: Please read the docs before opening an issue.